Repository uor16x/ofc-service, pull requests merged in 2022-06, with the labels that each got.

#35 Bug fixes and improvements
  client/src/app/app.component.html
  client/src/app/app.component.scss
  client/src/app/app.component.ts
  client/src/app/common/services/index.ts
  client/src/app/common/services/menu.service.ts
  client/src/app/common/services/socket.service.ts
  client/src/app/common/services/toast.service.ts
  client/src/app/pages/game/game.page.html
  client/src/app/pages/game/game.page.ts
  client/src/app/pages/lobby/host-modal/host-modal.component.ts
  client/src/app/pages/lobby/lobby.module.ts
  client/src/app/pages/lobby/lobby.page.html
  client/src/app/pages/lobby/lobby.page.ts
  client/src/app/shared/components/spinner/spinner.component.html
  client/src/app/shared/components/spinner/spinner.component.scss
  client/src/app/shared/components/spinner/spinner.component.ts
  client/src/app/shared/shared.module.ts
  server.js
  src/controllers/game.js
  src/sockets/socket.js
  src/sockets/sockets-state.js
Labels: refactor, frontend, backend

#37 Delete game; game schema refactor
  client/src/app/app.component.ts
  client/src/app/common/services/game.service.ts
  client/src/app/common/services/socket.service.ts
  client/src/app/pages/game/game.page.ts
  client/src/app/pages/lobby/game/game/game-item.component.html
  client/src/app/pages/lobby/game/game/game-item.component.scss
  client/src/app/pages/lobby/game/game/game-item.component.ts
  client/src/environments/environment.ts
  src/controllers/game.js
  src/db.js
  src/models/game.js
  src/models/hand.js
  src/sockets/socket.js
  src/sockets/sockets-state.js
Labels: feature, frontend, backend

#38 Schema and response fix
  src/models/game.js
  src/routes/game.js
Labels: refactor, backend

#40 Totals for lines added to route schema;
  src/routes/calculation.js
Labels: feature, backend

#42 Added json editor for game state
  client/package-lock.json
  client/package.json
  client/src/app/app.module.ts
  client/src/app/common/services/socket.service.ts
  client/src/app/pages/game/game-state/game-state.component.html
  client/src/app/pages/game/game-state/game-state.component.scss
  client/src/app/pages/game/game-state/game-state.component.ts
  client/src/app/pages/game/game.module.ts
  client/src/app/pages/game/game.page.html
  client/src/app/pages/game/game.page.ts
  client/src/global.scss
  src/sockets/socket.js
  src/sockets/sockets-state.js
Labels: feature, frontend

#43 Settings & translations
  client/src/app/pages/game/cards-picker/cards-picker.component.html
  client/src/app/pages/game/player-hand/player-hand.component.html
  client/src/app/pages/lobby/host-modal/host-modal.component.html
  client/src/app/pages/lobby/lobby.page.html
  client/src/app/pages/settings/settings.page.html
  client/src/app/pages/settings/settings.page.scss
  client/src/assets/i18n/en.json
  client/src/assets/i18n/ua.json
Labels: feature, frontend

#46 Empty card list schema;
  src/routes/calculation.js
Labels: bug, backend

#47 Remove redundant reload on lang switch
  client/src/app/pages/settings/settings.page.ts
Labels: bug, frontend

#49 Build config fix
  client/android/app/src/main/AndroidManifest.xml
  client/src/environments/environment.prod.ts
  client/src/environments/environment.ts
Labels: frontend

#57 Config and get version endpoint
  server.js
  src/config.json
  src/controllers/version.js
  src/route.js
  src/routes/version.js
Labels: feature, backend

#58 Version check
  client/android/app/build.gradle
  client/src/app/app.component.ts
  client/src/app/common/services/menu.service.ts
  client/src/app/common/services/modal.service.ts
  client/src/app/common/services/toast.service.ts
  client/src/app/pages/settings/settings.page.html
  client/src/app/pages/settings/settings.page.scss
  client/src/app/pages/settings/settings.page.ts
  client/src/app/shared/components/index.ts
  client/src/app/shared/components/modal/modal.component.html
  client/src/app/shared/components/modal/modal.component.scss
  client/src/app/shared/components/modal/modal.component.ts
  client/src/app/shared/index.ts
  client/src/app/shared/shared.module.ts
  client/src/assets/i18n/en.json
  client/src/assets/i18n/ua.json
  client/src/environments/environment.prod.ts
  client/src/environments/environment.ts
  client/src/global.scss
  src/controllers/version.js
  src/routes/version.js
Labels: feature, frontend
