Repository uor16x/ofc-service, pull requests merged in 2022-05, with the labels that each got.

#1 Fastify app singletone;
  server.js
  src/app.js
  src/route.js
  src/socket.js
Labels: enhancement

#2 Calc POST endpoint init
  .env.example
  .eslintrc.json
  .gitignore
  src/controller.js
Labels: enhancement

#3 Mongoose + db;
  .env.example
  package-lock.json
  package.json
  server.js
  src/db.js
Labels: enhancement

#4 Db schemas and game CRUD APIs
  .gitignore
  src/controllers/calculation.js
  src/controllers/game.js
  src/db.js
  src/helpers/err.js
  src/helpers/id-validator.js
  src/models/combination.js
  src/models/game.js
  src/models/hand.js
  src/route.js
  src/routes/calculation.js
  src/routes/game.js
Labels: enhancement

#6 Export codestyle refactor;
  src/helpers/id-validator.js
  src/routes/game.js
Labels: feature

#7 Extra line removed;
  src/controllers/game.js
Labels: refactor

#13 Action logs
  src/app.js
  src/controllers/action.js
  src/db.js
  src/models/action.js
  src/route.js
  src/routes/action.js
Labels: feature

#14 Get all games endpoint
  src/controllers/game.js
  src/routes/game.js
Labels: feature

#22 Disable main eslint for client
  .eslintignore
  package.json
Labels: frontend

#23 Project structure refactor; prettier; nickname auth
  client/package-lock.json
  client/package.json
  client/src/app/app-routing.module.ts
  client/src/app/app.component.scss
  client/src/app/app.module.ts
  client/src/app/common/guards/nickname.guard.ts
  client/src/app/common/interceptors/apikey.interceptor.ts
  client/src/app/common/models/game.interface.ts
  client/src/app/common/models/index.ts
  client/src/app/common/services/game.service.ts
  client/src/app/common/services/index.ts
  client/src/app/common/services/user.service.ts
  client/src/app/modules/main.module.ts
  client/src/app/pages/game/game-routing.module.ts
  client/src/app/pages/game/game.module.ts
  client/src/app/pages/game/game.page.html
  client/src/app/pages/game/game.page.ts
  client/src/app/pages/history/history-routing.module.ts
  client/src/app/pages/history/history.module.ts
  client/src/app/pages/history/history.page.html
  client/src/app/pages/history/history.page.ts
  client/src/app/pages/lobby/game/game/game-item.component.html
  client/src/app/pages/lobby/game/game/game-item.component.ts
  client/src/app/pages/lobby/host-modal/host-modal.component.html
  client/src/app/pages/lobby/host-modal/host-modal.component.ts
  client/src/app/pages/lobby/lobby-routing.module.ts
  client/src/app/pages/lobby/lobby.page.ts
  client/src/app/pages/login/login-routing.module.ts
  client/src/app/pages/login/login.module.ts
  client/src/app/pages/login/login.page.html
  client/src/app/pages/login/login.page.scss
  client/src/app/pages/login/login.page.ts
  client/src/app/pages/settings/settings-routing.module.ts
  client/src/environments/environment.prod.ts
  client/src/global.scss
  client/src/index.html
  client/src/main.ts
  client/src/polyfills.ts
  client/src/test.ts
  client/src/theme/variables.scss
Labels: refactor, frontend

#25 Host game
  client/src/app/app.component.html
  client/src/app/app.component.ts
  client/src/app/common/dtos/create-game.dto.ts
  client/src/app/common/dtos/index.ts
  client/src/app/common/services/game.service.ts
  client/src/app/common/services/user.service.ts
  client/src/app/pages/lobby/host-modal/host-modal.component.html
  client/src/app/pages/lobby/host-modal/host-modal.component.scss
  client/src/app/pages/lobby/host-modal/host-modal.component.ts
  client/src/app/pages/lobby/lobby.module.ts
  client/src/app/pages/lobby/lobby.page.ts
  client/src/app/pages/login/login.page.html
  client/src/app/pages/login/login.page.scss
  client/src/global.scss
  src/controllers/game.js
Labels: feature, frontend

#29 Calc moved to service;
  src/controllers/calculation.js
  src/routes/calculation.js
  src/services/calc.js
Labels: refactor, backend

#31 Game UI, logic and sockets
  client/angular.json
  client/package-lock.json
  client/package.json
  client/src/app/app.component.ts
  client/src/app/app.module.ts
  client/src/app/common/guards/nickname.guard.ts
  client/src/app/common/models/game.ts
  client/src/app/common/services/index.ts
  client/src/app/common/services/socket.service.ts
  client/src/app/pages/game/cards-picker/cards-picker.component.ts
  client/src/app/pages/game/game.module.ts
  client/src/app/pages/game/game.page.html
  client/src/app/pages/game/game.page.scss
  client/src/app/pages/game/game.page.ts
  client/src/app/pages/game/player-hand/player-hand.component.html
  client/src/app/pages/game/player-hand/player-hand.component.scss
  client/src/app/pages/game/player-hand/player-hand.component.ts
  client/src/app/pages/lobby/host-modal/host-modal.component.ts
  client/src/app/pages/login/login.page.ts
  client/src/app/shared/pipes/stat.pipe.ts
  client/src/app/shared/shared.module.ts
  client/src/assets/fonts/Jura/Jura-Bold.ttf
  client/src/assets/fonts/Jura/Jura-Light.ttf
  client/src/assets/fonts/Jura/Jura-Medium.ttf
  client/src/assets/fonts/Jura/Jura-Regular.ttf
  client/src/assets/fonts/Jura/Jura-SemiBold.ttf
  client/src/assets/fonts/fonts-Jura.css
  client/src/environments/environment.ts
  client/src/global.scss
  client/src/theme/variables.scss
  server.js
  src/models/game.js
  src/socket.js
  src/sockets-state.js
Labels: feature, frontend, backend
